- hosts: gitlab
  become: true
  vars_files:
    - ansible/ansible-role-gitlab-1/vars/main.yml
  roles:
    - role: ansible-role-gitlab
  hosts: jenkins
  become: true
  roles:
    - role: jenkins-role
